### ISSUE TITLE
Capsule throws an exception if the proxy URL is malformed 

### ISSUE THREAD

**Issue by pditommaso** [puniverse/capsule-maven#10]
When proxy environment variable contains a trailing slash like the following: 

```
HTTP_PROXY=http://proxy.crg.es:8881/
```

Capsule will throw the exception shown below:

```
CAPSULE EXCEPTION: For input string: "8881/" while processing attribute Allow-Snapshots: false
java.lang.NumberFormatException: For input string: "8881/"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:492)
    at java.lang.Integer.parseInt(Integer.java:527)
    at capsule.SystemProxySelector.addProxyFromEnv(SystemProxySelector.java:99)
    at capsule.SystemProxySelector.init(SystemProxySelector.java:68)
    at capsule.SystemProxySelector.<init>(SystemProxySelector.java:56)
    at capsule.SystemProxySelector.<init>(SystemProxySelector.java:48)
    at capsule.DependencyManager.newRepositorySession(DependencyManager.java:202)
    at capsule.DependencyManager.getSession(DependencyManager.java:186)
    at capsule.DependencyManager.setRepos(DependencyManager.java:134)
    at MavenCapsule.setDependencyRepositories(MavenCapsule.java:267)
    at MavenCapsule.initDependencyManager(MavenCapsule.java:247)
    at MavenCapsule.getDependencyManager(MavenCapsule.java:237)
    at MavenCapsule.resolve0(MavenCapsule.java:211)
    at Capsule.resolve(Capsule.java:3356)
    at Capsule.resolve(Capsule.java:3370)
    at Capsule.buildJavaProcess(Capsule.java:2214)
    at Capsule.buildProcess0(Capsule.java:1519)
    at Capsule.buildProcess(Capsule.java:1510)
    at Capsule.buildProcess(Capsule.java:1510)
    at Capsule.buildProcess(Capsule.java:1510)
    at Capsule.prelaunch0(Capsule.java:1483)
    at Capsule.prelaunch(Capsule.java:1476)
    at CapsuleLoader.prelaunch(CapsuleLoader.java:45)
    at Capsule.prepareForLaunch(Capsule.java:1329)
    at Capsule.launch(Capsule.java:1258)
    at Capsule.main0(Capsule.java:394)
    at Capsule.main(Capsule.java:374)
```

**Comment by pditommaso** [comment]
Are you going to release a new version anytime soon ?

**Comment by circlespainter** [comment]
The release date hasn't been defined yet but I've just published a `1.0.2-SNAPSHOT` containing the fix on SonaType. I'll close here, thanks!

**Comment by pditommaso** [comment]
:+1:

**Comment by pditommaso** [comment]
Still no plan for the release of `1.0.2` version?

**Comment by pron** [comment]
Next week.

**Comment by pditommaso** [comment]
Great, thanks.

**Comment by pditommaso** [comment]
Any chance to have a new release including this patch out ?

**Comment by pron** [comment]
I think the SNAPSHOT contains the fix, no? As for a release, we may do one next week, but no promises.

**Comment by pditommaso** [comment]
Yes, but I would like to avoid to rely on a snapshot dependency in my stable distribution.

**Comment by pron** [comment]
Well, we hoped to work on #13 before cutting a release, but if we don't get around to it next week (and if no one submits a PR), we'll release without it.

**Comment by pditommaso** [comment]
Gentle reminder.

**Comment by pron** [comment]
Done :)

**Comment by pditommaso** [comment]
:clap: 

Thanks.
