### ISSUE TITLE
User JAR file path cannot be added to a custom classpath 

### ISSUE THREAD

**Issue by pditommaso** [puniverse/capsule-maven#2]
maven caplet should allow users to include their own jars to the classpath overriding the `attribute` method. 

Currently the `sanitize` method does not allow that and raises the following exception: 

```
CAPSULE EXCEPTION: Could not resolve item /Users/pditommaso/workspace/nextflow/gradle/wrapper/gradle-wrapper.jar
java.lang.RuntimeException: Could not resolve item /Users/pditommaso/workspace/nextflow/gradle/wrapper/gradle-wrapper.jar
    at Capsule.resolve(Capsule.java:2781)
    at Capsule.buildClassPath(Capsule.java:1858)
    at Capsule.buildJavaProcess(Capsule.java:1744)
    at Capsule.buildProcess0(Capsule.java:1273)
    at Capsule.buildProcess(Capsule.java:1264)
    at Capsule.buildProcess(Capsule.java:1264)
    at Capsule.buildProcess(Capsule.java:1264)
    at Capsule.prelaunch0(Capsule.java:1237)
    at Capsule.prelaunch(Capsule.java:1232)
    at CapsuleLoader.prelaunch(CapsuleLoader.java:45)
    at Capsule.prepareForLaunch(Capsule.java:1146)
    at Capsule.launch(Capsule.java:1091)
    at Capsule.main0(Capsule.java:332)
    at Capsule.main(Capsule.java:311)
Caused by: java.lang.IllegalArgumentException: Path /Users/pditommaso/workspace/nextflow/gradle/wrapper/gradle-wrapper.jar is not local to app cache /Users/pditommaso/.nextflow/capsule/apps/nextflow_0.13.0-SNAPSHOT
    at Capsule.sanitize(Capsule.java:3003)
    at Capsule.resolve(Capsule.java:2768)
    ... 13 more
Unable to initialize nextflow environment
```

https://groups.google.com/d/msg/capsule-user/1kkx8-Y58R0/E95C17QL4ZoJ

**Comment by pron** [comment]
This is the wrong project :)
Could you re-submit to https://github.com/puniverse/capsule/issues?
Thanks!

**Comment by pditommaso** [comment]
Oops
